"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EventContentFilterMapping = exports.OCCURRENCE_SUMMARY_FIELDS = exports.EVENT_SUMMARY_TOP_VIEW_FIELDS = exports.EVENT_SUMMARY_FIELDS = void 0;
exports.EVENT_SUMMARY_FIELDS = [
    '_next_occurrences',
    'description',
    'hashtags',
    'id',
    'lang',
    'number_of_attendees',
    'owner',
    'privacy',
    'status',
    'title',
    'type',
    'version',
    'event_curated_image_id',
];
exports.EVENT_SUMMARY_TOP_VIEW_FIELDS = [
    '_next_occurrences',
    'description',
    'id',
    'lang',
    'number_of_attendees',
    'owner',
    'privacy',
    'status',
    'title',
    'type',
    'version',
    'event_curated_image_id',
];
exports.OCCURRENCE_SUMMARY_FIELDS = [
    'broadcast_summary',
    'circle_emoji',
    'description',
    'end_date',
    'id',
    'is_commenting_enabled',
    'owner_id',
    'start_date',
    'title',
    'type',
];
exports.EventContentFilterMapping = {
    science: ['parentscience', 'neuroscience', 'psychology', 'sciencemedicine', 'sportscience'],
    newage: ['newage', 'metaphysics', 'newagemysticism', 'astrology'],
    secular: ['secular', 'naturalenvironment', 'secularmindfulness'],
    religion: [
        'religion',
        'bahaifaith',
        'bhaktimovement',
        'christianity',
        'confucianism',
        'hinduism',
        'islam',
        'jainism',
        'judaism',
        'shinto',
        'sikhism',
        'sufism',
        'taoism',
        'traditionalbuddhism',
    ],
    spirituality: [
        'parentspirituality',
        'consciousness',
        'spirituality',
        'contemporarybuddhism',
        'nonduality',
        'energybased',
        'vedictradition',
        'alternativemedicine',
        'shamanism',
        'kabbalah',
        'yogalibrary_item.hashtags.13001.name_in_app',
    ],
};
//# sourceMappingURL=event.model.js.map